In [2]:
x = [4,2,8,9,3]
max_value = max(x)
max_value

9

In [3]:
argmax = x.index(max_value)
argmax

3

In [4]:
import numpy as np
max_value = np.max(x)
max_value

9

In [5]:
argmax = np.argmax(x)
argmax

3

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('./data/house_prices.csv')

In [9]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [10]:
df.iloc[2,4]

0.469

In [11]:
df.iloc[3,5]

6.998

In [13]:
df.iloc[2,3] + df.iloc[4,5]

7.147

In [17]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [18]:
A

array([[1, 2],
       [3, 4]])

In [19]:
B

array([[5, 6],
       [7, 8]])

In [20]:
C = np.concatenate((A,B), axis=0)

In [21]:
C

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [22]:
C.shape

(4, 2)

In [24]:
X = df[['CRIM', 'NOX', 'RM', 'AGE','TAX']]

In [25]:
X

CRIM    NOX     RM   AGE  TAX
0    0.00632  0.538  6.575  65.2  296
1    0.02731  0.469  6.421  78.9  242
2    0.02729  0.469  7.185  61.1  242
3    0.03237  0.458  6.998  45.8  222
4    0.06905  0.458  7.147  54.2  222
..       ...    ...    ...   ...  ...
501  0.06263  0.573  6.593  69.1  273
502  0.04527  0.573  6.120  76.7  273
503  0.06076  0.573  6.976  91.0  273
504  0.10959  0.573  6.794  89.3  273
505  0.04741  0.573  6.030  80.8  273

[506 rows x 5 columns]

In [26]:
X_t = np.transpose(X)

In [27]:
X_t

0          1          2          3          4          5    \
CRIM    0.00632    0.02731    0.02729    0.03237    0.06905    0.02985   
NOX     0.53800    0.46900    0.46900    0.45800    0.45800    0.45800   
RM      6.57500    6.42100    7.18500    6.99800    7.14700    6.43000   
AGE    65.20000   78.90000   61.10000   45.80000   54.20000   58.70000   
TAX   296.00000  242.00000  242.00000  222.00000  222.00000  222.00000   

            6          7          8          9    ...       496        497  \
CRIM    0.08829    0.14455    0.21124    0.17004  ...    0.2896    0.26838   
NOX     0.52400    0.52400    0.52400    0.52400  ...    0.5850    0.58500   
RM      6.01200    6.17200    5.63100    6.00400  ...    5.3900    5.79400   
AGE    66.60000   96.10000  100.00000   85.90000  ...   72.9000   70.60000   
TAX   311.00000  311.00000  311.00000  311.00000  ...  391.0000  391.00000   

            498        499        500        501        502        503  \
CRIM    0.23912    0.17783    0.22438    0.06263    0.04527    0.06076   
NOX     0.58500    0.58500    0.58500    0.57300    0.57300    0.57300   
RM      6.01900    5.56900    6.02700    6.59300    6.12000    6.97600   
AGE    65.30000   73.50000   79.70000   69.10000   76.70000   91.00000   
TAX   391.00000  391.00000  391.00000  273.00000  273.00000  273.00000   

            504        505  
CRIM    0.10959    0.04741  
NOX     0.57300    0.57300  
RM      6.79400    6.03000  
AGE    89.30000   80.80000  
TAX   273.00000  273.00000  

[5 rows x 506 columns]

In [36]:
XtX=X_t@X
XtX

CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [29]:
X_t.dot(X)

CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [30]:
A = df[['CRIM', 'NOX', 'NOX']]
A

CRIM    NOX    NOX
0    0.00632  0.538  0.538
1    0.02731  0.469  0.469
2    0.02729  0.469  0.469
3    0.03237  0.458  0.458
4    0.06905  0.458  0.458
..       ...    ...    ...
501  0.06263  0.573  0.573
502  0.04527  0.573  0.573
503  0.06076  0.573  0.573
504  0.10959  0.573  0.573
505  0.04741  0.573  0.573

[506 rows x 3 columns]

In [31]:
AtA = A.T@A
AtA

CRIM         NOX         NOX
CRIM  43970.343555  1226.12317  1226.12317
NOX    1226.123170   162.47038   162.47038
NOX    1226.123170   162.47038   162.47038

In [33]:
np.linalg.det(AtA)

0.0

In [37]:
XtX_inv = np.linalg.inv(XtX)
XtX_inv

array([[ 4.07613803e-05,  1.32526683e-04,  4.76832932e-05,
        -1.01889386e-06, -1.10744437e-06],
       [ 1.32526683e-04,  3.44301609e-01, -1.30762150e-02,
        -8.56047279e-04, -1.21234099e-04],
       [ 4.76832932e-05, -1.30762150e-02,  9.05341934e-04,
         1.73338529e-05,  1.03814433e-06],
       [-1.01889386e-06, -8.56047279e-04,  1.73338529e-05,
         5.35211609e-06,  4.19638894e-09],
       [-1.10744437e-06, -1.21234099e-04,  1.03814433e-06,
         4.19638894e-09,  1.58047038e-07]])

In [38]:
XtX @ XtX_inv

0             1             2             3             4
CRIM  1.000000e+00 -6.979357e-14  7.898703e-16 -1.089894e-15 -3.591367e-17
NOX  -1.610639e-17  1.000000e+00 -1.769057e-16 -3.317590e-17 -5.661019e-19
RM    2.097955e-16 -3.839137e-15  1.000000e+00 -1.547972e-16 -6.737559e-18
AGE  -2.352290e-15 -7.866743e-13  6.373451e-14  1.000000e+00  4.474723e-16
TAX  -4.461919e-15 -1.942029e-12  7.933252e-14 -7.646276e-15  1.000000e+00

In [39]:
XtX_inv @ XtX

CRIM           NOX            RM           AGE           TAX
0  1.000000e+00 -9.976309e-16 -1.049198e-14 -1.335187e-13 -7.702802e-13
1  1.450356e-13  1.000000e+00  1.243199e-13  2.092731e-12  1.189994e-11
2 -1.244734e-14 -1.753764e-15  1.000000e+00 -1.830795e-13 -1.243143e-12
3  2.089321e-16 -2.301382e-18  4.416128e-16  1.000000e+00  1.970463e-14
4  2.864010e-17  1.812250e-18  6.748655e-17  1.530867e-16  1.000000e+00

In [40]:
crim = df['CRIM']
nox = df['NOX']

In [41]:
res = np.inner(crim, nox)
res

1226.123170231

In [44]:
covX = X_t.dot(X)
covX

CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [46]:
e, v = np.linalg.eig(covX)

In [47]:
e

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [48]:
v

array([[ 1.17248568e-02, -4.34541539e-02, -9.89273583e-01,
         1.38967257e-01, -3.78876853e-04],
       [ 1.21545113e-03,  3.97729110e-03,  5.48368537e-03,
         3.74537281e-02, -9.99274663e-01],
       [ 1.28461807e-02,  4.11504926e-02,  1.37240647e-01,
         9.88869506e-01,  3.79962757e-02],
       [ 1.54544362e-01,  9.86199762e-01, -4.66395497e-02,
        -3.66695593e-02,  2.48287726e-03],
       [ 9.87832003e-01, -1.54313263e-01,  1.72471505e-02,
        -8.81831838e-03,  3.51466736e-04]])